{% set version = "1.19.1" %}
{% set vtk_version = "9.1.0" %}
{% set netcdf4_version = "1.5.8" %}

package:
  name: python-mint
  version: {{ version }}

source:
  url: https://github.com/pletzer/mint/archive/v{{ version }}.tar.gz
  sha256: 7cdd2f7c09f92e996866d0c01899f91c6e58a1f9332aac766c05c13a3ed86e2c

build:
  number: 1
  skip: true  # [py<39 or py>39]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
  host:
    - python
    - cython
    - libnetcdf
    - pip
    - setuptools
    - tbb-devel
    - vtk ={{ vtk_version }}
  run:
    - python
    - libnetcdf 
    - numpy
    - netcdf4
    - vtk ={{ vtk_version }}

test:
  imports:
    - mint

about:
  home: https://github.com/pletzer/mint
  license: 0BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Mimetic INTerpolation on the Sphere.
  description: |
    mint regrids edge centred fields from a source to a destination grid.
    The grid is stored as a collection of grid cells, which have four vertices
    (i.e., the cells are quadrilaterals). The edge field is stored as integrals
    of a vector field along each edge. The vertex coordinates are stored in
    longitude-latitude space. The regridding method is mimetic in the sense that
    Stokes's theorem is satisfied to near machine precision. In particular, the
    loop integrals of an interpolated vector field deriving from a gradient is zero.

extra:
  recipe-maintainers:
    - pletzer
    - bjlittle
