{% set version = "1.28.0" %}
{% set vtk_version = "9.2.5" %}

package:
  name: python-mint
  version: {{ version }}

source:
  url: https://github.com/pletzer/mint/archive/v{{ version }}.tar.gz
  sha256: f280dfefba404912010e447e2934827c44c8eb167c2f2d58ebbcaccb04a66f1c

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
  host:
    - python
    - cython
    - pip
    - setuptools
    - tbb-devel
    - vtk ={{ vtk_version }}
    - scitools-iris
  run:
    - python
    - numpy
    - netcdf4
    - vtk ={{ vtk_version }}
    - scitools-iris

test:
  imports:
    - mint

about:
  home: https://github.com/pletzer/mint
  license: 0BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Mimetic INTerpolation on the Sphere.
  description: |
    mint regrids edge centred fields from a source to a destination grid.
    The grid is stored as a collection of grid cells, each having four vertices
    (i.e., the cells are quadrilaterals) in longitude-latitude space. 
    The edge field is stored as integrals of a vector field along each edge. 
    The regridding method is mimetic in the sense that
    Stokes's theorem is satisfied to near machine precision. In particular, the
    loop integrals of an interpolated vector field deriving from a gradient is zero.

extra:
  recipe-maintainers:
    - pletzer
    - bjlittle
