{% set version = "1.18.3" %}
{% set vtk_version = "9.0.3" %}

package:
  name: python-mint
  version: {{ version }}

source:
  url: https://github.com/pletzer/mint/archive/v{{ version }}.tar.gz
  sha256: 8ef5ebbd363f0bb0c1d89d1a45788adabcf0f4d7da85570a7b25cb854bd5a6fc

build:
  number: 0
  skip: True  # [py<37 or py>39]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libGL-devel') }}
  host:
    - python
    - cython
    - libnetcdf
    - pip
    - setuptools
    - tbb-devel
    - vtk ={{ vtk_version }}
  run:
    - python
    - libnetcdf 
    - numpy
    - vtk ={{ vtk_version }}

test:
  imports:
    - mint

about:
  home: https://github.com/pletzer/mint
  license: 0BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Mimetic INTerpolation on the Sphere.
  description: |
    mint regrids edge centred fields from a source to a destination grid.
    The grid is stored as a collection of grid cells, which have four vertices
    (i.e., the cells are quadrilaterals). The edge field is stored as integrals
    of a vector field along each edge. The vertex coordinates are stored in
    longitude-latitude space. The regridding method is mimetic in the sense that
    Stokes's theorem is satisfied to near machine precision. In particular, the
    loop integrals of an interpolated vector field deriving from a gradient is zero.

extra:
  recipe-maintainers:
    - pletzer
    - bjlittle
