{% set version = "1.26.0" %}
{% set vtk_version = "9.1.0" %}

package:
  name: python-mint
  version: {{ version }}

source:
  url: https://github.com/pletzer/mint/archive/v{{ version }}.tar.gz
  sha256: 11806ece952b48b2780246e56f39725d855a16e2b3c1c9184f0ad52239665c6d

build:
  number: 0
  skip: true  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
  host:
    - python
    - cython
    - pip
    - setuptools
    - tbb-devel
    - libnetcdf
    - vtk ={{ vtk_version }}
  run:
    - python
    - numpy
    - netcdf4
    - libnetcdf
    - vtk ={{ vtk_version }}

test:
  imports:
    - mint

about:
  home: https://github.com/pletzer/mint
  license: 0BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Mimetic INTerpolation on the Sphere.
  description: |
    mint regrids edge centred fields from a source to a destination grid.
    The grid is stored as a collection of grid cells, each having four vertices
    (i.e., the cells are quadrilaterals) in longitude-latitude space. 
    The edge field is stored as integrals of a vector field along each edge. 
    The regridding method is mimetic in the sense that
    Stokes's theorem is satisfied to near machine precision. In particular, the
    loop integrals of an interpolated vector field deriving from a gradient is zero.

extra:
  recipe-maintainers:
    - pletzer
    - bjlittle
