conda_forge_output_validation: true
provider:
  linux_64: azure
  osx_64: azure
  win_64: azure
azure:
  settings_win:
    pool:
      vmImage: windows-2019
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
