conda_forge_output_validation: true
provider:
  linux: azure
  osx: azure
  win: azure
azure:
  settings_win:
    pool:
      vmImage: windows-2019
github:
  branch_name: main
  tooling_branch_name: main
